desport_site_index:
    path:     /
    defaults: { _controller: DesportPanelBundle:Default:index }
    
desport_csv:
    path:     /csv/
    defaults: { _controller: DesportPanelBundle:Default:loadCSVClients }
    
desport_login_success:
    path:     /loginsuccess
    defaults: { _controller: DesportPanelBundle:Default:loginSuccess }
desport_profile_edit:
    path:     /profile/
    defaults: { _controller: DesportPanelBundle:User:profile }

desport_admin_dashboard:
    path:     /admin/
    defaults: { _controller: DesportPanelBundle:Default:dashboard }
desport_sales_dashboard:
    path:     /sales/
    defaults: { _controller: DesportPanelBundle:Default:dashboard }

desport_sales_client_index:
    path:     /sales/client/
    defaults: { _controller: DesportPanelBundle:Client:index }
desport_sales_client_load_table:
    path:     /sales/client/loadTable/{page}
    defaults: { _controller: DesportPanelBundle:Client:loadTable }
desport_sales_client_load_table_self:
    path:     /sales/client/loadTableSelf/{page}
    defaults: { _controller: DesportPanelBundle:Client:loadTableSelf }
desport_sales_client_new:
    path:     /sales/client/new/
    defaults: { _controller: DesportPanelBundle:Client:new }
desport_sales_client_view:
    pattern:     /sales/client/view/{client_id}/
    defaults: { _controller: DesportPanelBundle:Client:view }
desport_sales_client_edit:
    pattern:     /sales/client/edit/{client_id}/
    defaults: { _controller: DesportPanelBundle:Client:edit }
desport_sales_client_stage:
    pattern:     /sales/client/stage/{client_id}/
    defaults: { _controller: DesportPanelBundle:Client:stage }
desport_sales_client_contact:
    pattern:     /sales/client/contact/{client_id}/
    defaults: { _controller: DesportPanelBundle:Client:contact }
desport_sales_client_messages:
    pattern:     /sales/client/messages/{client_id}/
    defaults: { _controller: DesportPanelBundle:Message:client }
desport_sales_client_messages_page:
    pattern:     /sales/client/messages/{client_id}/page/{page_number}/
    defaults: { _controller: DesportPanelBundle:Message:client }
desport_sales_client_messages_page_max:
    pattern:     /sales/client/messages/{client_id}/page/{page_number}/max/{max_results}/
    defaults: { _controller: DesportPanelBundle:Message:client }
    
desport_sales_messages_index:
    pattern:     /sales/client/message/
    defaults: { _controller: DesportPanelBundle:Message:index }
desport_sales_messages_view:
    pattern:     /sales/client/message/view/{message_id}/
    defaults: { _controller: DesportPanelBundle:Message:view }
desport_sales_messages_ticket_view:
    pattern:     /sales/client/message/ticket/{ticket_id}/
    defaults: { _controller: DesportPanelBundle:Message:ticket }
desport_sales_messages_attachment:
    pattern:     /sales/client/message/attachment/{attachment_id}/
    defaults: { _controller: DesportPanelBundle:Message:attachment }
desport_sales_messages_attachment_keep:
    pattern:     /sales/client/message/attachment/{attachment_id}/keep/
    defaults: { _controller: DesportPanelBundle:Message:attachmentKeep }
desport_sales_messages_attachment_unkeep:
    pattern:     /sales/client/message/attachment/{attachment_id}/unkeep/
    defaults: { _controller: DesportPanelBundle:Message:attachmentUnkeep }
desport_sales_messages_transfer:
    pattern:     /sales/client/message/transfer/{message_id}/{user_id}/
    defaults: { _controller: DesportPanelBundle:Message:transfer }
desport_sales_messages_setunread:
    pattern:     /sales/client/message/setunread/{message_id}/
    defaults: { _controller: DesportPanelBundle:Message:unread }
desport_sales_messages_ticketcreate:
    pattern:     /sales/client/message/ticket/create/{message_id}/
    defaults: { _controller: DesportPanelBundle:Message:ticketCreate }
desport_sales_messages_ticketstate:
    pattern:     /sales/client/message/ticket/state/{message_id}/{state}
    defaults: { _controller: DesportPanelBundle:Message:ticketState }
desport_sales_messages_automessage_load_level:
    pattern:     /sales/client/message/automessage/{client_id}/loadlevel
    defaults: { _controller: DesportPanelBundle:Message:automessageLoadLevel }
desport_sales_messages_automessage_fill:
    pattern:     /sales/client/message/fill/{automessage_id}
    defaults: { _controller: DesportPanelBundle:Message:automessageFill }

desport_sales_events_index:
    pattern:     /sales/event/index/
    defaults: { _controller: DesportPanelBundle:Event:index }
desport_sales_client_events:
    pattern:     /sales/event/client/{client_id}/
    defaults: { _controller: DesportPanelBundle:Event:client }
    
desport_sales_site_index:
    path:     /sales/site/
    defaults: { _controller: DesportPanelBundle:Site:index }
desport_sales_site_new:
    pattern:     /sales/site/new/{client_id}/
    defaults: { _controller: DesportPanelBundle:Site:new }
desport_sales_site_view:
    pattern:     /sales/site/view/{site_id}/
    defaults: { _controller: DesportPanelBundle:Site:view }

desport_sales_site_install:
    pattern:     /sales/site/install/{site_id}/
    defaults: { _controller: DesportPanelBundle:Site:install }
desport_sales_site_install_stage:
    pattern:     /sales/site/install/{site_id}/stage/{stage_id}/
    defaults: { _controller: DesportPanelBundle:Site:installStage }
desport_sales_site_install_undo:
    pattern:     /sales/site/install/{site_id}/undo/{stage_id}/
    defaults: { _controller: DesportPanelBundle:Site:installUndoStage }
desport_sales_site_load_product:
    pattern:     /sales/site/install/{site_id}/load/{product_id}/
    defaults: { _controller: DesportPanelBundle:Site:loadProduct }
    
desport_api_mailgun_message_new:
    path:     /api/mailgun/message/new/
    defaults: { _controller: DesportPanelBundle:API:mailgunMessageNew }
desport_api_mailgun_message_drop:
    path:     /api/mailgun/message/drop/
    defaults: { _controller: DesportPanelBundle:API:mailgunMessageDrop }