desport_admin_dashboard:
    path:     /admin/
    defaults: { _controller: DesportPanelBundle:Default:dashboard }

desport_sales_client_index:
    path:     /sales/client/
    defaults: { _controller: DesportPanelBundle:Client:index }
desport_sales_client_new:
    path:     /sales/client/new/
    defaults: { _controller: DesportPanelBundle:Client:new }
desport_sales_client_view:
    pattern:     /sales/client/view/{client_id}/
    defaults: { _controller: DesportPanelBundle:Client:view }
desport_sales_client_edit:
    pattern:     /sales/client/edit/{client_id}/
    defaults: { _controller: DesportPanelBundle:Client:edit }
desport_sales_client_stage:
    pattern:     /sales/client/stage/{client_id}/
    defaults: { _controller: DesportPanelBundle:Client:stage }
    
    
desport_sales_site_index:
    path:     /sales/site/
    defaults: { _controller: DesportPanelBundle:Site:index }
desport_sales_site_new:
    pattern:     /sales/site/new/{client_id}
    defaults: { _controller: DesportPanelBundle:Site:new }
desport_sales_site_view:
    pattern:     /sales/site/view/{site_id}/
    defaults: { _controller: DesportPanelBundle:Site:view }
    
desport_sales_site_install_stage:
    pattern:     /sales/site/install/{site_id}/stage/{stage_id}
    defaults: { _controller: DesportPanelBundle:Site:installStage }
desport_sales_site_install_undo:
    pattern:     /sales/site/install/{site_id}/undo/{stage_id}
    defaults: { _controller: DesportPanelBundle:Site:installUndo }
    