services:
#    desport_panel.example:
#        class: Desport\PanelBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

parameters:
    desport.install.class: Desport\PanelBundle\Controller\InstallController
 
services:
    desport.install:
        class: "%desport.install.class%"